version: 2

project_name: external-secrets-federation

env:
  - CGO_ENABLED=0

builds:
  - id: federation
    main: ./cmd/federation
    binary: federation
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: federation-archives
    builds:
      - federation
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - id: federation-docker
    use: docker
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Tag }}-{{ .Arch }}"
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Major }}.{{ .Minor }}-{{ .Arch }}"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--platform=linux/{{ .Arch }}"
      - "--build-arg=TARGETOS={{ .Os }}"
      - "--build-arg=TARGETARCH={{ .Arch }}"
    skip_push: false

docker_manifests:
  - name_template: "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Tag }}-arm64"
  - name_template: "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Major }}.{{ .Minor }}-amd64"
      - "{{ .Env.DOCKER_REGISTRY | default \"ghcr.io/external-secrets-inc\" }}/federation-server:{{ .Major }}.{{ .Minor }}-arm64"

sboms:
  - artifacts:
      - archive
      - docker

signs:
  - id: cosign-docker
    cmd: cosign
    artifacts: docker
    args:
      - sign
      - "--key=${COSIGN_KEY}"
      - "${artifact}"
    env:
      - COSIGN_EXPERIMENTAL=1
    skip: "{{ eq (env `COSIGN_KEY`) `` }}"
  - id: cosign-checksums
    cmd: cosign
    artifacts: checksum
    args:
      - sign-blob
      - "--key=${COSIGN_KEY}"
      - "--output-signature=${signature}"
      - "${artifact}"
    env:
      - COSIGN_EXPERIMENTAL=1
    skip: "{{ eq (env `COSIGN_KEY`) `` }}"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

helm:
  - name: federation-server
    chart: deploy/charts/federation
    version: "{{ .Version }}"
    appVersion: "{{ .Version }}"
    repository: "{{ .Env.HELM_REPOSITORY | default \"oci://ghcr.io/external-secrets-inc/charts\" }}"
    skip_push: false
