//go:build !ignore_autogenerated

/*
Copyright © 2025 ESO Maintainer Team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedGenerator) DeepCopyInto(out *AllowedGenerator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedGenerator.
func (in *AllowedGenerator) DeepCopy() *AllowedGenerator {
	if in == nil {
		return nil
	}
	out := new(AllowedGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedGeneratorState) DeepCopyInto(out *AllowedGeneratorState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedGeneratorState.
func (in *AllowedGeneratorState) DeepCopy() *AllowedGeneratorState {
	if in == nil {
		return nil
	}
	out := new(AllowedGeneratorState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authorization) DeepCopyInto(out *Authorization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authorization.
func (in *Authorization) DeepCopy() *Authorization {
	if in == nil {
		return nil
	}
	out := new(Authorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Authorization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationList) DeepCopyInto(out *AuthorizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Authorization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationList.
func (in *AuthorizationList) DeepCopy() *AuthorizationList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationSpec) DeepCopyInto(out *AuthorizationSpec) {
	*out = *in
	out.FederationRef = in.FederationRef
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(FederationSubject)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedClusterSecretStores != nil {
		in, out := &in.AllowedClusterSecretStores, &out.AllowedClusterSecretStores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedGenerators != nil {
		in, out := &in.AllowedGenerators, &out.AllowedGenerators
		*out = make([]AllowedGenerator, len(*in))
		copy(*out, *in)
	}
	if in.AllowedGeneratorStates != nil {
		in, out := &in.AllowedGeneratorStates, &out.AllowedGeneratorStates
		*out = make([]AllowedGeneratorState, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationSpec.
func (in *AuthorizationSpec) DeepCopy() *AuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizedIdentity) DeepCopyInto(out *AuthorizedIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizedIdentity.
func (in *AuthorizedIdentity) DeepCopy() *AuthorizedIdentity {
	if in == nil {
		return nil
	}
	out := new(AuthorizedIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizedIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizedIdentityList) DeepCopyInto(out *AuthorizedIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizedIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizedIdentityList.
func (in *AuthorizedIdentityList) DeepCopy() *AuthorizedIdentityList {
	if in == nil {
		return nil
	}
	out := new(AuthorizedIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizedIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizedIdentitySpec) DeepCopyInto(out *AuthorizedIdentitySpec) {
	*out = *in
	in.IdentitySpec.DeepCopyInto(&out.IdentitySpec)
	if in.IssuedCredentials != nil {
		in, out := &in.IssuedCredentials, &out.IssuedCredentials
		*out = make([]IssuedCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizedIdentitySpec.
func (in *AuthorizedIdentitySpec) DeepCopy() *AuthorizedIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizedIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationOIDC) DeepCopyInto(out *FederationOIDC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationOIDC.
func (in *FederationOIDC) DeepCopy() *FederationOIDC {
	if in == nil {
		return nil
	}
	out := new(FederationOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationRef) DeepCopyInto(out *FederationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationRef.
func (in *FederationRef) DeepCopy() *FederationRef {
	if in == nil {
		return nil
	}
	out := new(FederationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationSpiffe) DeepCopyInto(out *FederationSpiffe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationSpiffe.
func (in *FederationSpiffe) DeepCopy() *FederationSpiffe {
	if in == nil {
		return nil
	}
	out := new(FederationSpiffe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationSubject) DeepCopyInto(out *FederationSubject) {
	*out = *in
	if in.Spiffe != nil {
		in, out := &in.Spiffe, &out.Spiffe
		*out = new(FederationSpiffe)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(FederationOIDC)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationSubject.
func (in *FederationSubject) DeepCopy() *FederationSubject {
	if in == nil {
		return nil
	}
	out := new(FederationSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySpec) DeepCopyInto(out *IdentitySpec) {
	*out = *in
	out.FederationRef = in.FederationRef
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(FederationSubject)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySpec.
func (in *IdentitySpec) DeepCopy() *IdentitySpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuedCredential) DeepCopyInto(out *IssuedCredential) {
	*out = *in
	in.SourceRef.DeepCopyInto(&out.SourceRef)
	if in.RemoteRef != nil {
		in, out := &in.RemoteRef, &out.RemoteRef
		*out = new(RemoteRef)
		**out = **in
	}
	if in.StateRef != nil {
		in, out := &in.StateRef, &out.StateRef
		*out = new(StateRef)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadBinding != nil {
		in, out := &in.WorkloadBinding, &out.WorkloadBinding
		*out = new(WorkloadBinding)
		**out = **in
	}
	in.LastIssuedAt.DeepCopyInto(&out.LastIssuedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuedCredential.
func (in *IssuedCredential) DeepCopy() *IssuedCredential {
	if in == nil {
		return nil
	}
	out := new(IssuedCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteRef) DeepCopyInto(out *RemoteRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteRef.
func (in *RemoteRef) DeepCopy() *RemoteRef {
	if in == nil {
		return nil
	}
	out := new(RemoteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateRef) DeepCopyInto(out *StateRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateRef.
func (in *StateRef) DeepCopy() *StateRef {
	if in == nil {
		return nil
	}
	out := new(StateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadBinding) DeepCopyInto(out *WorkloadBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadBinding.
func (in *WorkloadBinding) DeepCopy() *WorkloadBinding {
	if in == nil {
		return nil
	}
	out := new(WorkloadBinding)
	in.DeepCopyInto(out)
	return out
}
